### ISSUE TITLE
Props for the project; one suggestion: would it be possible to add some (simple) examples, perhaps ideally of simple ruby gems, including possible problems/pitfalls?

### ISSUE THREAD

**Issue by rubyFeedback** [DocSpring/ruby_crystal_codemod#1]
Hey Nathan,

First off, props for the project. I myself suggested on the ruby tracker something similar years ago. Not exactly the same, mind you, but I wanted something that could translate from ruby to crystal and back again.

My idea back then was to use rubocop (odd ideas I do have) ... 

Back then sorbet/types were not existing. In the future that may be the case. But anyway I digress.

Specifically I would like to suggest to add a few examples of real ruby code, and how that may be (automatically) translated into crystal. Rubocop has this autocorrect option, which I found useful to update old ruby code to a version I can deal with in an easier way (because it actually improves on that old code, too, and can be adjusted to the style used in a project).

My suggestion is: Would it be possible for you, when you have time in the coming months, to add a FEW examples of existing ruby gems, and translating them into crystal THROUGh ruby-crystal-codemod? Just really small gems in size so that the work load is kept small. Perhaps some code could be added in example/tutorial directories or so to demo this. (Simple gems because this lessens the work load for you AND for people who want to get started; many people love examples because it is much easier for them to read what is happening on the commandline.)

I am curious whether sorbet will make your life simpler - the additional information should in theory make it simpler onto the crystal side, since we'd then have information from within ruby directly. That would be quite a speed improvement - people could write ruby yet execute that in crystal (well ... at the least that is what I think would be possible), so IF this is the case eventually then this would be pretty epic.

Best regards for the future!

Robert

**Comment by ndbroadbent** [comment]
Hi Robert, thanks for your message! I think `rubocop` would also be a good choice, but I chose `rufo` because it can be a little bit faster and I found it easier to modify the formatting code.

This is a great suggestion about trying to convert some existing Ruby gems and adding some more examples. This is definitely the main reason why I started the project, because I am trying to see if I can convert some Ruby libraries into Crystal libraries. I chose this small [`bad-words.ruby`](https://github.com/hairyhum/bad-words.ruby) gem as my initial project so I've been working towards that goal, but it turns out that it's a lot harder than I expected! 

Automatic conversion becomes impossible as soon as Crystal requires type annotations (e.g. for instance variables in classes), so I'm exploring a way to instrument Ruby files and automatically record the types for variables and methods. ([See the issue I recently opened on the Sorbet project.](https://github.com/sorbet/sorbet/issues/2315)) The idea would be to use Sorbet type annotations as an intermediate step, because this is the only way to convert most Ruby files to Crystal.

Thanks again for your feedback, and I will try to add some more examples in the future!
